### ISSUE TITLE
Lookahead fails partial match

### ISSUE THREAD

**Issue by vkz** [cgrand/seqexp#3]
Do I misunderstand how lookahead works or this is incorrect behavior?
```clj
;; from your test-suite
(se/exec (se/cat (se/*? se/_) (se/?= odd?) (se/as :a (se/* se/_))) [2 4 5 6 8])
;; => match
(se/exec (se/cat (se/*? se/_) (se/?= odd?)) [2 4 5 6 8])
;; => nil
;; would've expected
;; {:match '(2 4)
;;  :rest '(5 6 8)}
```

**Comment by cgrand** [comment]
Yesterday I thought it would be hard to resolve the tension between `exec` laziness (the `:rest` may still be partially unrealized) and testing remaining lookaheads against `:rest`.
However now that I've slept on it I realize it's related to a common complaint: that `(:match (se/exec (se/+? :a) [:a :a]))` is `(:a :a)`and not `(:a)`.
Both problems are related to the longest match policy. I refined it: when an accept state is reached only the _non-accepting threads of higher priority_ will be used in an attempt to find a longest match.
So it's fixed by https://github.com/cgrand/seqexp/commit/2a4f8e28286df5f312114837f8042f19185040fd
